# -*- coding: utf-8 -*-
"""100 primers números Fibonacci

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GsbiQTKSEKU9KO7ADStGzKC3Cz5L7QxI
"""

f=open('mifichero.txt','w')
lista=[0,1]
fibo=[]
for i in range(1,99):
  c=lista[i]
  h=i-1
  p=c+lista[h]
  lista.append(p)

f.write(str(lista))
f.close()

from google.colab import files
files.download('mifichero.txt')