# -*- coding: utf-8 -*-
"""Alex.Molina.Bucles

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gvFKc1Uwm9M3npVHQrln9FukEepmIV4B

**Exercici 1** - Imprimir els números entre el 5 i el 20, saltant de tres en tres
"""

for i in range(5,20,3):
  print(i)

"""**Exerci 2** - Imprimir tots els números correlatius entre l&#39;ingressat per l&#39;usuari i un menys del doble d&#39;aquest."""

n=int(input("Posa un nombre enter positiu: "))
n2=n*2
for i in range(n,n2):
  print(i)

"""**Exercici 3** - Imprimir un llistat de les vocals que
apareixen en aquesta frase
"""

f=input("Posa una frase: ")
for i in f:
  if i=='a'or'A':
    print("a")
    break
for i in f:
  if i=='e'or'E':
    print("e")
    break
for i in f:
  if i=='i'or'I':
    print("i")
    break
for i in f:
  if i=='o'or'O':
    print("o")
    break
for i in f:
  if i=='u'or'U':
    print("u")
    break

"""**Exercici 4** - Sol·licitar a l&#39;usuari que ingressi una frase i després imprimir la quantitat de vocals que es
troben en aquesta frase
"""

f=input("Posa una frase: ")
conta=0
for i in f:
  if i=='a':
    conta+=1
conte=0
for i in f:
  if i=='e':
    conte+=1
conti=0
for i in f:
  if i=='i':
    conti+=1
conto=0
for i in f:
  if i=='o':
    conto+=1
contu=0
for i in f:
  if i=='u':
    contu+=1
print("La quantitats de a és de: ",conta)
print("La quantitats de e és de: ",conte)
print("La quantitats de i és de: ",conti)
print("La quantitats de o és de: ",conto)
print("La quantitats de u és de: ",contu)
print("La suma de totes les vocals es de ",conta+conte+contu+conto+conti)

"""**Exercici 5** - Escriure un programa que mostri la sumatòria de tots els números entre el 0 i el 100."""

c=0
for i in range(0,101):
  c+=i
print(c)

"""**Exercici 6** - Escriure un programa que mostri la sumatòria de tots els múltiples de 3 trobats entre el 0 i el
100.
"""

s=0
for i in range(0,101):
  if i%3==0:
    s+=i
print(i)

"""**Exercici 7** - Donat un nombre enter positiu, mostrar el seu factorial."""

n=int(input("Posa un nombre enter positiu: "))
c=1
n=n+1
for i in range(1,n):
  c*=i
print(c)

"""**Exercici 8** - Crear un algorisme que mostri els primers 10 números de la successió de Fibonacci."""

lista=[0,1]
z=int(lista[0]+lista[1])
lista.append(z)
u=int(lista[1]+lista[2])
lista.append(u)
d=int(lista[2]+lista[3])
lista.append(d)
t=int(lista[3]+lista[4])
lista.append(t)
q=int(lista[4]+lista[5])
lista.append(q)
c=int(lista[5]+lista[6])
lista.append(c)
s=int(lista[6]+lista[7])
lista.append(s)
siete=int(lista[7]+lista[8])
lista.append(siete)
print(lista)

"""**Exercici 9** - Escriure un programa que permeti a l&#39;usuari ingressar 6 nombres enters i mostrar la sumatòria dels números negatius i la mitjana dels
positius.
"""

c=0
cont=0
p=0
n1=int(input("Posa un nombre enter: "))
if n1 < 0:
  c-=n1
else:
  p+=n1
  cont+=1
n2=int(input("Posa un nombre enter: "))
if n2 < 0:
  c-=n2
else:
  p+=n2
  cont+=1
n3=int(input("Posa un nombre enter: "))
if n3 < 0:
  c-=n3
else:
  p+=n3
  cont+=1
n4=int(input("Posa un nombre enter: "))
if n4 < 0:
  c-=n4
else:
  p+=n4
  cont+=1
n5=int(input("Posa un nombre enter: "))
if n5 < 0:
  c-=n5
else:
  p+=n5
  cont+=1
n6=int(input("Posa un nombre enter: "))
if n6 < 0:
  c-=n6
else:
  p+=n6
  cont+=1
if p>0:
  mitjana=p/cont
else:
  mitjana=0
print("Sumatoria de números negatius ",-c,"\nMitjana números positius ",mitjana)

"""  **Exercici 10** - Escriu un programa que permeti xifrar els 5 missatges.
El corriment (quantitat de llocs que es correran les lletres) serà donat per l’usuari abans
de començar a encriptar.
Els 5 missatges faran servir el mateix corriment.
"""

m=input("Posa el missatge que vols encriptar: ")
corriment=int(input("Quantes vegades vols correr la lletra? "))
lista=['a','b','c','d','e','f','g','h','i','j','k','l','m','n','ñ','o','p','q','r','s','t','u','v','w','x','y','z','a','b','c','d','e','f','g','h','i','j','k','l','m','n','ñ','o','p','q','r','s','t','u','v','w','x','y','z','a','b','c','d','e','f','g','h','i','j','k','l','m','n','ñ','o','p','q','r','s','t','u','v','w','x','y','z']
m=m.lower()
h=m.replace(' ','')
for i in range(0,len(h)):
  c=int(lista.index(h[i]))+corriment
  print(lista[c])

"""**Exercici 11** - Escriure un programa que permeti a l&#39;usuari ingressar dos anys i després imprimeixi tots els
anys en aquest rang, que siguin de traspàs i múltiples de 10.
"""

c=[]
t=[]
any1=int(input("Posa un any: "))
any2=int(input("Posa un altre any: "))
if any1 > any2:
  p=any1
  any1=any2
  any2=p
  for i in range(any1,any2):
   if i % 10 == 0:
      c.append(i)
   elif i % 4==0:
      if i % 100!=0:
        t.append(i)
      elif i % 100 == 0 and i % 400 == 0:
       t.append(i)
else:
  for i in range(any1,any2):
   if i % 10 == 0:
      c.append(i)
   elif i % 4==0:
      if i % 100!=0:
        t.append(i)
      elif i % 100 == 0 and i % 400 == 0:
       t.append(i)
print("Anys multiples de 10: ",c)
print("Anys de traspàs: ",t)