# -*- coding: utf-8 -*-
"""Alex.Molina.Conceptes.Bàsics

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1We52i_gNdfDw9djrYnFEuVvFrNW4e3C7

**Exercici** **1** - Fer diferents operacions
"""

a=int(input("Posa un número: "))
b=int(input("Posa un número: "))
print("El número guardat a la variable a es ",a)
print("El número guardat b la variable a es ",b)
c= a+b
print("El resultat de la suma es ",c)
d= a-b
print("El resultat de la resta es ",d)
e= a*b
print("El resultat de la multipliació es ",e)
f= a/b
print("El resultat de la divisió es ",f)

"""**Exercici 2** - Canviar dues variables"""

a=int(input("Valor de a: "))
b=int(input("Valor de b: "))
print("Intercanvi fet!")
c=b
print("Valor de a: ",c)
c=a
print("Valor de b: ",c)

"""**Exercici 3** - Fer un càlcul d'una operació"""

a=int(input("Valor de a: "))
b=int(input("Valor de b: "))
print(a,"+",b,"/2*","(",a,"+",b,")")
print(a,"+",b,"/2*",a+b)
c=a+b
print(a,"+",b,"/",2*c)
d=2*c
print(a,"+",round(b/d,3))
e=b/d
print(round(a+e,3))

"""**Exercici 4** - Mostrar el número anterior y posterior"""

a=int(input("Posa un número: "))
print(a-1)
print(a+1)

"""**Exercici 5** - Fer una mitjana de 4 notes"""

notas1=int(input("Posa 1 nota entre l'1 i el 10: "))
notas2=int(input("Posa 1 nota entre l'1 i el 10: "))
notas3=int(input("Posa 1 nota entre l'1 i el 10: "))
notas4=int(input("Posa 1 nota entre l'1 i el 10: "))
notas=notas1+notas2+notas3+notas4
nn=notas/4
print(nn)

"""**Exercici 6** - Fer el perímetre i l’àrea d'un rectangle"""

base=int(input("Posa la base d'un recntangle: "))
alçada=int(input("Posa l'alçada d'un rectangle: "))
p=base+alçada+base+alçada
print("El perímetre del rectangle és de ",p)
a=base*alçada
print("L'àrea del rectangle és de ",a)

"""**Exercici 7** - Demana una quantitat de minuts i mostra per pantalla a quantes hores i minuts correspon"""

min=int(input("Posa una quantitat de minuts: "))
h=min/60
hmin=min/60
c=(hmin-int(h))*60
print(min,"minuts són ",int(h),"hores i ",int(c),"minuts")

"""**Exercici 8** - Sumar una hora a segons"""

h=int(input("Posa una hora entre 0 i 23: "))
min=int(input("Posa un minut entre el 0 i 59: "))
s=int(input("Posa uns segon entre el 0 i 59: "))
segons=h*3600 + min*60 + s
print("L'hora introduïda és ",h," : ",min," : ",s," que correspon a ",segons," segons")

"""**Exercici 9** - Demana el pressupost del mes i mostra quants diners gastarà en cada cosa"""

pre=float(input("Quin pressupost pel mes tens? "))
print("Has gastat: ",round(pre*0.15,2)," en menjar")
print("Has gastat: ",round(pre*0.6,2)," en jocs")
print("Has gastat: ",round(pre*0.25,2)," en material otaku")

"""**Exercici 10** - Demana el pressupost del mes i mostra quants diners gastarà en cada cosa"""

dt=float(input("Quants diners tens per comprar la peça de roba? "))
pp=float(input("Quant val la peça de roba? "))
print("Aquest serà el preu amb un 25% de descompte: ",pp*0.75)
print("Aquests seràn els diners que et quedaràn després de fer la compra: ",dt-(pp*0.75))