# -*- coding: utf-8 -*-
"""Alex.Molina.Bucles2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B4MvLviVJ8_vXAqP-atbJCqwka97TeRE

**Exercici 1**- Escriure un programa que demani a l&#39;usuari un nombre enter i mostri per pantalla un
triangle rectangle com el de més avall, d&#39;alçada el número introduït.
"""

n = int(input("Introduce la altura: "))
for i in range(n):
   print("*"*(i+1))

"""**Exercici 2** - Escriure un programa que demani a l&#39;usuari un número enters més gran que 2 i
mostri per pantalla si és un nombre primer o no.
"""

num=int(input("Pon un número: "))
while num <= 2:
  print("El número tiene que ser mas grande que 1")
  num=int(input("Pon un numero: "))
c=0
for i in range(2,num):
  if i < num:
    if num % i == 0:
      c+=1
    else:
      c+=0
if c >= 1:
  print("No es un nombre primer")
else:
  print("Es un nombre primer")

"""**Exercici 3** - Escriure un programa que mostri el ressò de tot allò que l&#39;usuari introdueixi fins que
l&#39;usuari escrigui “sortir” que s&#39;acabarà.
"""

s=input("Posa una frase: ")
print(s)
s=''
while s!= "sortir":
  s=input("Posa una frase: ")
  print(s)

"""**Exercici 4** - Escriviu un programa que demani un nombre enter més gran que zero i que escrigui
els seus divisors.
"""

lista=[]
n=int(input("Posa un nombre més gran que 0: "))
for i in range(1,n+1):
  if n % i == 0:
    lista.append(i)
print("Els divisors son",lista)

"""**Exercici 5** - Escriviu un programa que pregunti quants números s&#39;introduiran, demaneu aquests
números, si el número introduït no es més gran que l&#39;anterior, haurà de mostrar un
missatge informant-nos del error i terminar donant-nos les gràcies, si sempre són
major al introduir-los tots ens donarà les gràcies.
"""

lista=[]
cont=0
por=0
con=int(input("Quants números vols introduir: "))
for i in range(0,con):
  if i <= con:
    n=input("Possa un número: ")
    lista.append(n)
    cont+=1
    if cont >= 2:
      if lista[por] < lista[por-1]:
        print("ERROR")
        print("Gràcies per participar")
        break
      else:
        print("Gràcies")
        por+=1
        continue
    else:
      por+=1
      continue

"""**Exercici 6** - Escriviu un programa que demani dos nombres enters positius i escriviu la suma detots els enters des del primer número fins al segon. Escriviu la suma realitzada mostrant tots el nombres."""

n1=int(input("Posa un número: "))
n2=int(input("Posa un número: "))
c=0
h=[]
for i in range(n1,n2+1):
  h.append(str(i))
  c+=i
p='+'.join(h)
print(p,"=",c)

"""**Exercici 7** - Escriviu un programa que pregunti quants números s&#39;introduiran, demaneu aquests
números, i escriviu el major, el menor i la mitjana aritmètica.
"""

lista=[]
tre=0
c=0
n=int(input("Quants números vols introduir? "))
for i in range(0,n):
  if i <= n:
    con=int(input("Possa un número: "))
    lista.append(con)
for i in lista:
  c+=i
  tre+=1
mitjana=c/tre
print("El número més gran és: " , max(lista))
print("El número més petit és: ",min(lista))
print("La mitjana és: ",mitjana)

"""**Exercici 8** - Donat un número, compteu el nombre total de dígits d&#39;un número. Per exemple, el número és 75869, de manera que la sortida hauria de ser 5."""

n=int(input("Possa un número: "))
c=0
for i in str(n):
  c+=1
print(c)

"""**Exercici 9** - Joc endevinar número 1-100"""

import random
r=random.randint(1,100)
print("EL JOC D'ENDEVINAR UN NÚMERO")
cont=0
while cont < 5:
  n=int(input("Possa un número: "))
  if n < r:
    print("Massa petit")
    cont+=1
    continue
  elif n > r:
    print("Massa gran")
    cont+=1
    continue
  elif n == r:
    print("FELICITATS, has encertat el número!!")
    break
if cont == 5:
  print("Has perdut")

"""**Exercici 10** - Escriviu un programa que demani una frase i una vocal. A continuació substituïu
totes les vocals de la frase per la vocal triada i mostri el resultat per pantalla.
"""

f=input("Possa una frase: ")
v=input("Possa una vocal: ")
for letra in f:
  if letra == 'a':
    f.replace(letra, v)

for letra in f:
  if letra == 'e':
    f.replace(letra, v)

for letra in f:
  if letra == 'i':
    f.replace(letra, v)

for letra in f:
  if letra == 'o':
    f.replace(letra, v)

for letra in f:
  if letra == 'u':
    f.replace(letra, v)
print(f)