# -*- coding: utf-8 -*-
"""EXERCICI GRÀFIC - Àlex Molina

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kyzXctDOFbpbjqXkPoUo1UkCUIU6wv1T

**EXERCICI GRÀFIC AMB GOOGLE COLAB. REPRESENTACIÓ DE RECTES**

Farem un programa que ens representi la recta que li indiquem:

De la recta        y = ax + b        el programa em demana el pendent (a) i l'ordenada a l'origen (b)  i un interval [xmín, xmàx], i em representa la recta en aquell interval 

Per millorar el programa, poseu títols als eixos, diferents colors.

**Programa para probar**
"""

a=int(input("Posa la pendent: "))
b=int(input("Posa l'ordenada de l'origen: ")) 

x=[]
y=[]

h=b/a
h=str(h)
if h < '0':
  xmin=b/a
  xmax=(-2*b)/a
  temp=xmin
  interv=(int(xmax)-int(min))/100
  for i in range(0,100):
    temp+=interv
    x.append(temp)
    p=a*i+b
    y.append(p)
else:
  xmin=(-2*b)/a
  xmax=b/a
  temp=xmin
  interv=(xmax-xmin)/100
  for i in range(0,100):
    temp+=interv
    x.append(temp)
    p=a*i+b
    y.append(p)


import matplotlib.pyplot as plt
plt.plot(x, y, label="Línia")

plt.axhline(y=0, color="black", linestyle="-")
plt.axvline(color="black")
plt.xlim(xmin, xmax)
plt.legend(fontsize=18)

plt.plot()

plt.xlabel("eje x")
plt.ylabel("eje y")
plt.title("Gràfica")
plt.legend()
plt.show()

"""**Programa bien hecho**"""

import numpy as np   #para cuestiones matemáticas y=x*a+b
import matplotlib.pyplot as plt

a=float(input("Posa la a: "))
b=float(input("Posa la b: "))

xmin=b/a          #calcul xmin
xmax=-2*b/a       #calcul xmax

x=np.linspace(xmin, xmax, 30)
y=x*a+b

plt.axhline(y=0, color="red", linestyle="-")
plt.axvline(x=0, color="red")
plt.xlim(min(xmin,xmax),max(xmin,xmax))
#plt.legend(fontsize=18)

plt.xlabel("eje x", fontsize=15, color='black', alpha=0.8)
plt.ylabel("eje y", fontsize=15, color='black', alpha=0.8)
plt.title("Ejercicio gráfica")
plt.xlim(min(xmin,xmax),max(xmin,xmax))
tit='Gàfica de: y='+str(a)+'x +'+str(b)+'\n'
plt.title(tit, fontsize=20, color='black')

plt.plot(x,y)
plt.show()